In [1]:
# magic function para hacer que los graficos de matplotlib se renderizen en el notebook.
%matplotlib inline

import datetime as datetime
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

plt.style.use('default') # Make the graphs a bit prettier
plt.rcParams['figure.figsize'] = (15, 5)

In [ ]:
#Buscamos relacioens entre la falta de servicio y el clima.
weather = pd.read_csv('./data/weather.csv', low_memory=False, parse_dates=['date'])
weather.date = weather.date.dt.date
weather.to_csv("auxWeather.csv")
weather = pd.read_csv('./auxWeather.csv', low_memory=False,)
weather = weather.loc[:,["date" , "max_temperature_f", "mean_temperature_f" , "min_temperature_f", "max_dew_point_f", "mean_dew_point_f", "min_dew_point_f", "max_humidity", "mean_humidity", "min_humidity", "max_sea_level_pressure_inches", "mean_sea_level_pressure_inches", "min_sea_level_pressure_inches", "max_visibility_miles", "mean_visibility_miles", "min_visibility_miles", "max_wind_Speed_mph", "mean_wind_speed_mph", "max_gust_speed_mph", "precipitation_inches", "cloud_cover", "events", "wind_dir_degrees", "zip_code"]]
weather[:10]

In [96]:
NotDocks = pd.read_csv('./NotDocks.csv', low_memory=True)
NotDocks['date'] = NotDocks['time']
NotDocks = NotDocks.loc[:,['date','id','zipCode']]
NotDocks[:10]

         date  id  zipCode
0  2013-11-03   2    95113
1  2013-11-03   2    95113
2  2013-11-03   2    95113
3  2013-11-03   2    95113
4  2013-12-04   2    95113
5  2013-12-04   2    95113
6  2013-12-04   2    95113
7  2013-12-04   2    95113
8  2013-12-04   2    95113
9  2013-12-04   2    95113

In [65]:
NotBike = pd.read_csv('./NotBike.csv', low_memory=True)
NotBike['date'] = NotBike['time']
NotBike = NotBike.loc[:,['date','id','zipCode']]
NotBike[:10]

         date  id  zipCode
0  2013-11-03   2    95113
1  2013-11-03   2    95113
2  2013-11-03   2    95113
3  2013-11-03   2    95113
4  2013-12-04   2    95113
5  2013-12-04   2    95113
6  2013-12-04   2    95113
7  2013-12-04   2    95113
8  2013-12-04   2    95113
9  2013-12-04   2    95113

In [103]:
# Divido por ciudad.
NotBike95113 = NotBike.groupby('zipCode')
NotBike95113 = NotBike95113.get_group(95113)
NotBike95113[:10]

         date  id  zipCode
0  2013-11-03   2    95113
1  2013-11-03   2    95113
2  2013-11-03   2    95113
3  2013-11-03   2    95113
4  2013-12-04   2    95113
5  2013-12-04   2    95113
6  2013-12-04   2    95113
7  2013-12-04   2    95113
8  2013-12-04   2    95113
9  2013-12-04   2    95113

In [105]:
#Calculo cuantas veces al dia no hay bisicletas disponibles
DataBike = NotBike95113['date'].value_counts()
df_a = pd.DataFrame(DataBike)
df_a.to_csv("aux95113.csv")     
aux95113 = pd.read_csv('aux95113.csv', low_memory=False)
aux95113['cantidad'] = aux95113['date']
aux95113 = aux95113.loc[:,['cantidad','Unnamed: 0']]
aux95113['date'] = aux95113['Unnamed: 0']
aux95113 = aux95113.loc[:,['cantidad','date']]
aux95113[:10]

   cantidad        date
0      1282  2014-07-25
1      1044  2014-11-10
2      1023  2014-11-09
3       768  2015-03-11
4       756  2014-11-08
5       682  2014-10-10
6       661  2013-09-22
7       651  2014-09-10
8       629  2014-09-15
9       626  2014-08-10

In [106]:
#join
aux95113 = pd.merge(NotBike95113, aux95113, on='date', how='left')
aux95113[:10]

         date  id  zipCode  cantidad
0  2013-11-03   2    95113        37
1  2013-11-03   2    95113        37
2  2013-11-03   2    95113        37
3  2013-11-03   2    95113        37
4  2013-12-04   2    95113        70
5  2013-12-04   2    95113        70
6  2013-12-04   2    95113        70
7  2013-12-04   2    95113        70
8  2013-12-04   2    95113        70
9  2013-12-04   2    95113        70

In [81]:
#divido el clima por ciudad
weather95113 = weather.groupby('zip_code')
weather95113 = weather95113.get_group(95113)
weather95113[:5]

,date,max_temperature_f,mean_temperature_f,min_temperature_f,max_dew_point_f,mean_dew_point_f,min_dew_point_f,max_humidity,mean_humidity,min_humidity,...,mean_visibility_miles,min_visibility_miles,max_wind_Speed_mph,mean_wind_speed_mph,max_gust_speed_mph,precipitation_inches,cloud_cover,events,wind_dir_degrees,zip_code
736,2013-08-29,81.0,72.0,63.0,62.0,61.0,59.0,87.0,69.0,51.0,...,10.0,10.0,16.0,7.0,24.0,0,4.0,NaN,320.0,95113
737,2013-08-30,88.0,76.0,63.0,63.0,60.0,55.0,93.0,65.0,37.0,...,10.0,10.0,18.0,5.0,22.0,0,2.0,NaN,316.0,95113
738,2013-08-31,80.0,71.0,62.0,59.0,57.0,54.0,90.0,66.0,42.0,...,10.0,10.0,18.0,8.0,22.0,0,0.0,NaN,309.0,95113
739,2013-09-01,81.0,72.0,62.0,61.0,57.0,51.0,84.0,62.0,39.0,...,10.0,10.0,20.0,7.0,24.0,0,2.0,NaN,308.0,95113
740,2013-09-02,79.0,73.0,66.0,62.0,61.0,59.0,81.0,68.0,54.0,...,10.0,10.0,21.0,8.0,25.0,T,5.0,Rain,315.0,95113

In [107]:
#join
salida = pd.merge(weather95113, aux95113, on='date', how='inner')
salida[:5]

,date,max_temperature_f,mean_temperature_f,min_temperature_f,max_dew_point_f,mean_dew_point_f,min_dew_point_f,max_humidity,mean_humidity,min_humidity,...,mean_wind_speed_mph,max_gust_speed_mph,precipitation_inches,cloud_cover,events,wind_dir_degrees,zip_code,id,zipCode,cantidad
0,2013-08-29,81.0,72.0,63.0,62.0,61.0,59.0,87.0,69.0,51.0,...,7.0,24.0,0,4.0,NaN,320.0,95113,4,95113,127
1,2013-08-29,81.0,72.0,63.0,62.0,61.0,59.0,87.0,69.0,51.0,...,7.0,24.0,0,4.0,NaN,320.0,95113,4,95113,127
2,2013-08-29,81.0,72.0,63.0,62.0,61.0,59.0,87.0,69.0,51.0,...,7.0,24.0,0,4.0,NaN,320.0,95113,4,95113,127
3,2013-08-29,81.0,72.0,63.0,62.0,61.0,59.0,87.0,69.0,51.0,...,7.0,24.0,0,4.0,NaN,320.0,95113,4,95113,127
4,2013-08-29,81.0,72.0,63.0,62.0,61.0,59.0,87.0,69.0,51.0,...,7.0,24.0,0,4.0,NaN,320.0,95113,4,95113,127

In [108]:
#Busco relaciones 
#Como es de esperar no encuentro ninguna relacion fuerte.
salida.corr().loc[:,['cantidad']]

                                cantidad
max_temperature_f               0.280949
mean_temperature_f              0.239761
min_temperature_f               0.119441
max_dew_point_f                 0.291572
mean_dew_point_f                0.220878
min_dew_point_f                 0.118916
max_humidity                    0.142825
mean_humidity                  -0.012048
min_humidity                   -0.117040
max_sea_level_pressure_inches  -0.269724
mean_sea_level_pressure_inches -0.300901
min_sea_level_pressure_inches  -0.312790
max_visibility_miles            0.047298
mean_visibility_miles          -0.189255
min_visibility_miles           -0.208703
max_wind_Speed_mph             -0.081012
mean_wind_speed_mph            -0.203323
max_gust_speed_mph             -0.130875
cloud_cover                    -0.078747
wind_dir_degrees                0.050401
zip_code                             NaN
id                              0.050401
zipCode                              NaN
cantidad                        1.000000

In [112]:
#revisamos los Dock
#Otra vez nada. 
#Pero se remarca que como vimos en Status. Hay una fuerte relacion entre Que no halla bices y que no halla docks
NotDocks95113 = NotDocks.groupby('zipCode')
NotDocks95113 = NotDocks95113.get_group(95113)
DataBike = NotDocks95113['date'].value_counts()
df_a = pd.DataFrame(DataBike)
df_a.to_csv("aux95113.csv")  
aux95113 = pd.read_csv('aux95113.csv', low_memory=False)
aux95113['cantidad'] = aux95113['date']
aux95113 = aux95113.loc[:,['cantidad','Unnamed: 0']]
aux95113['date'] = aux95113['Unnamed: 0']
aux95113 = aux95113.loc[:,['cantidad','date']]
aux95113 = pd.merge(NotDocks95113, aux95113, on='date', how='inner')
salida = pd.merge(weather95113, aux95113, on='date', how='inner')
salida.corr().loc[:,['cantidad']]

                                cantidad
max_temperature_f               0.280949
mean_temperature_f              0.239761
min_temperature_f               0.119441
max_dew_point_f                 0.291572
mean_dew_point_f                0.220878
min_dew_point_f                 0.118916
max_humidity                    0.142825
mean_humidity                  -0.012048
min_humidity                   -0.117040
max_sea_level_pressure_inches  -0.269724
mean_sea_level_pressure_inches -0.300901
min_sea_level_pressure_inches  -0.312790
max_visibility_miles            0.047298
mean_visibility_miles          -0.189255
min_visibility_miles           -0.208703
max_wind_Speed_mph             -0.081012
mean_wind_speed_mph            -0.203323
max_gust_speed_mph             -0.130875
cloud_cover                    -0.078747
wind_dir_degrees                0.050401
zip_code                             NaN
id                              0.050401
zipCode                              NaN
cantidad                        1.000000

In [113]:
#Probamos con otra ciudad
#Aca notamos una fuerte relacion con wind_dir_degrees. Pero no vemos logico esta relacion. Debe ser una casualdiad
#Aca hay que tomar nota que esta
NotBike94063 = NotBike.groupby('zipCode')
NotBike94063 = NotBike94063.get_group(94063)
DataBike = NotBike94063['date'].value_counts()
df_a = pd.DataFrame(DataBike)
df_a.to_csv("aux94063.csv")  
aux94063 = pd.read_csv('aux94063.csv', low_memory=False)
aux94063['cantidad'] = aux94063['date']
aux94063 = aux95113.loc[:,['cantidad','Unnamed: 0']]
aux94063['date'] = aux94063['Unnamed: 0']
aux94063 = aux95113.loc[:,['cantidad','date']]
aux94063 = pd.merge(NotBike94063, aux94063, on='date', how='inner')
weather94063 = weather.groupby('zip_code')
weather94063 = weather94063.get_group(94063)
salida = pd.merge(weather94063, aux94063, on='date', how='inner')
salida.corr().loc[:,['cantidad']]

                                cantidad
max_temperature_f              -0.035958
mean_temperature_f             -0.040558
min_temperature_f               0.015242
max_dew_point_f                 0.157956
mean_dew_point_f               -0.166764
min_dew_point_f                -0.173953
max_humidity                   -0.311523
mean_humidity                  -0.322432
min_humidity                    0.027963
max_sea_level_pressure_inches  -0.294702
mean_sea_level_pressure_inches -0.277381
min_sea_level_pressure_inches  -0.168696
max_visibility_miles                 NaN
mean_visibility_miles           0.155735
min_visibility_miles            0.180001
max_wind_Speed_mph             -0.325248
mean_wind_speed_mph            -0.045358
max_gust_speed_mph              0.111955
cloud_cover                     0.189596
wind_dir_degrees               -0.811102
zip_code                             NaN
id                              0.175568
zipCode                              NaN
cantidad                        1.000000

In [97]:
#Docks
#aca notamos una relacion con max_humidity y wind_dir_degrees
#esto es la segunda vez wind_dir_degrees. 
#Aunque es logico ya que tiene fuerte relazion entre la falta de Docs y de vicis
NotDocks94063 = NotDocks.groupby('zipCode')
NotDocks94063 = NotDocks94063.get_group(94063)
DataBike = NotDocks94063['date'].value_counts()
df_a = pd.DataFrame(DataBike)
df_a.to_csv("aux94063.csv")  
aux94063 = pd.read_csv('aux94063.csv', low_memory=False)
aux94063['cantidad'] = aux94063['date']
aux94063 = aux95113.loc[:,['cantidad','Unnamed: 0']]
aux94063['date'] = aux94063['Unnamed: 0']
aux94063 = aux95113.loc[:,['cantidad','date']]
aux94063 = pd.merge(NotDocks94063, aux94063, on='date', how='inner')
salida = pd.merge(weather94063, aux94063, on='date', how='inner')
salida.corr().loc[:,['cantidad']]

                                cantidad
max_temperature_f               0.038948
mean_temperature_f             -0.105921
min_temperature_f              -0.229235
max_dew_point_f                -0.383957
mean_dew_point_f               -0.361895
min_dew_point_f                -0.208082
max_humidity                   -0.530947
mean_humidity                  -0.447548
min_humidity                   -0.280653
max_sea_level_pressure_inches  -0.252781
mean_sea_level_pressure_inches -0.254477
min_sea_level_pressure_inches  -0.217506
max_visibility_miles                 NaN
mean_visibility_miles           0.241685
min_visibility_miles            0.299910
max_wind_Speed_mph             -0.177132
mean_wind_speed_mph            -0.199380
max_gust_speed_mph              0.057569
cloud_cover                     0.176446
wind_dir_degrees               -0.625900
zip_code                             NaN
id                              0.175568
zipCode                              NaN
cantidad                        1.000000

In [93]:
#Probamos con otra ciudad
#aca sale el cloud_cover esto es mas logico. Lo tendremos en cuenta
NotBike94041 = NotBike.groupby('zipCode')
NotBike94041 = NotBike94041.get_group(94063)
DataBike = NotBike94041['date'].value_counts()
df_a = pd.DataFrame(DataBike)
df_a.to_csv("aux94041.csv")  
aux94041 = pd.read_csv('aux94041.csv', low_memory=False)
aux94041['cantidad'] = aux94041['date']
aux94041 = aux94041.loc[:,['cantidad','Unnamed: 0']]
aux94041['date'] = aux94041['Unnamed: 0']
aux94041 = aux94041.loc[:,['cantidad','date']]
aux94041 = pd.merge(NotBike94041, aux94041, on='date', how='inner')
weather94041 = weather.groupby('zip_code')
weather94041 = weather94041.get_group(94063)
salida = pd.merge(weather94041, aux94041, on='date', how='inner')
salida.corr().loc[:,['cantidad']]

                                cantidad
max_temperature_f               0.238944
mean_temperature_f              0.232934
min_temperature_f               0.180356
max_dew_point_f                 0.171650
mean_dew_point_f                0.261801
min_dew_point_f                 0.317943
max_humidity                   -0.061916
mean_humidity                  -0.011399
min_humidity                   -0.002244
max_sea_level_pressure_inches  -0.233284
mean_sea_level_pressure_inches -0.240659
min_sea_level_pressure_inches  -0.266903
max_visibility_miles                 NaN
mean_visibility_miles           0.206549
min_visibility_miles            0.242165
max_wind_Speed_mph             -0.078570
mean_wind_speed_mph             0.260543
max_gust_speed_mph             -0.136584
cloud_cover                     0.403995
wind_dir_degrees                0.108471
zip_code                             NaN
id                              0.115893
zipCode                              NaN
cantidad                        1.000000

In [100]:
#Docks
##aca sale cloud_cover. Pero como digimos antes es logico por la fuerte relacion.
NotDocks94041 = NotDocks.groupby('zipCode')
NotDocks94041 = NotDocks94041.get_group(94063)
DataBike = NotDocks94041['date'].value_counts()
df_a = pd.DataFrame(DataBike)
df_a.to_csv("aux94041.csv")  
aux94041 = pd.read_csv('aux94041.csv', low_memory=False)
aux94041['cantidad'] = aux94041['date']
aux94041 = aux94041.loc[:,['cantidad','Unnamed: 0']]
aux94041['date'] = aux94041['Unnamed: 0']
aux94041 = aux94041.loc[:,['cantidad','date']]
aux94041 = pd.merge(NotDocks94041, aux94041, on='date', how='inner')
salida = pd.merge(weather94041, aux94041, on='date', how='inner')
salida.corr().loc[:,['cantidad']]

                                cantidad
max_temperature_f               0.238944
mean_temperature_f              0.232934
min_temperature_f               0.180356
max_dew_point_f                 0.171650
mean_dew_point_f                0.261801
min_dew_point_f                 0.317943
max_humidity                   -0.061916
mean_humidity                  -0.011399
min_humidity                   -0.002244
max_sea_level_pressure_inches  -0.233284
mean_sea_level_pressure_inches -0.240659
min_sea_level_pressure_inches  -0.266903
max_visibility_miles                 NaN
mean_visibility_miles           0.206549
min_visibility_miles            0.242165
max_wind_Speed_mph             -0.078570
mean_wind_speed_mph             0.260543
max_gust_speed_mph             -0.136584
cloud_cover                     0.403995
wind_dir_degrees                0.108471
zip_code                             NaN
id                              0.115893
zipCode                              NaN
cantidad                        1.000000

In [94]:
#Probamos con otra ciudad
#No notamos nada.
NotBike94107 = NotBike.groupby('zipCode')
NotBike94107 = NotBike94107.get_group(94107)
DataBike = NotBike94107['date'].value_counts()
df_a = pd.DataFrame(DataBike)
df_a.to_csv("aux94107.csv")  
aux94107 = pd.read_csv('aux94107.csv', low_memory=False)
aux94107['cantidad'] = aux94107['date']
aux94107 = aux94107.loc[:,['cantidad','Unnamed: 0']]
aux94107['date'] = aux94107['Unnamed: 0']
aux94107 = aux94107.loc[:,['cantidad','date']]
aux94107 = pd.merge(NotBike94107, aux94107, on='date', how='inner')
weather94107 = weather.groupby('zip_code')
weather94107 = weather94107.get_group(94107)
salida = pd.merge(weather94107, aux94107, on='date', how='inner')
salida.corr().loc[:,['cantidad']]

                                cantidad
max_temperature_f               0.146702
mean_temperature_f              0.135418
min_temperature_f               0.090976
max_dew_point_f                 0.100033
mean_dew_point_f                0.101304
min_dew_point_f                 0.088672
max_humidity                    0.020786
mean_humidity                  -0.038293
min_humidity                   -0.064248
max_sea_level_pressure_inches  -0.052936
mean_sea_level_pressure_inches -0.043275
min_sea_level_pressure_inches  -0.039141
max_visibility_miles           -0.049372
mean_visibility_miles           0.058462
min_visibility_miles            0.107079
max_wind_Speed_mph              0.037194
mean_wind_speed_mph             0.051596
max_gust_speed_mph              0.052009
cloud_cover                    -0.076289
wind_dir_degrees                0.126398
zip_code                             NaN
id                             -0.012171
zipCode                              NaN
cantidad                        1.000000

In [114]:
#Dock
#Nada
NotDocks94107 = NotDocks.groupby('zipCode')
NotDocks94107 = NotDocks94107.get_group(94107)
DataBike = NotDocks94107['date'].value_counts()
df_a = pd.DataFrame(DataBike)
df_a.to_csv("aux94107.csv")  
aux94107 = pd.read_csv('aux94107.csv', low_memory=False)
aux94107['cantidad'] = aux94107['date']
aux94107 = aux94107.loc[:,['cantidad','Unnamed: 0']]
aux94107['date'] = aux94107['Unnamed: 0']
aux94107 = aux94107.loc[:,['cantidad','date']]
aux94107 = pd.merge(NotDocks94107, aux94107, on='date', how='inner')
weather94107 = weather.groupby('zip_code')
weather94107 = weather94107.get_group(94107)
salida = pd.merge(weather94107, aux94107, on='date', how='inner')
salida.corr().loc[:,['cantidad']]

                                cantidad
max_temperature_f               0.146702
mean_temperature_f              0.135418
min_temperature_f               0.090976
max_dew_point_f                 0.100033
mean_dew_point_f                0.101304
min_dew_point_f                 0.088672
max_humidity                    0.020786
mean_humidity                  -0.038293
min_humidity                   -0.064248
max_sea_level_pressure_inches  -0.052936
mean_sea_level_pressure_inches -0.043275
min_sea_level_pressure_inches  -0.039141
max_visibility_miles           -0.049372
mean_visibility_miles           0.058462
min_visibility_miles            0.107079
max_wind_Speed_mph              0.037194
mean_wind_speed_mph             0.051596
max_gust_speed_mph              0.052009
cloud_cover                    -0.076289
wind_dir_degrees                0.126398
zip_code                             NaN
id                             -0.012171
zipCode                              NaN
cantidad                        1.000000

In [95]:
#Probamos con otra ciudad
#Aca notamos relazion con casi todo. 
NotBike94301 = NotBike.groupby('zipCode')
NotBike94301 = NotBike94301.get_group(94301)
DataBike = NotBike94301['date'].value_counts()
df_a = pd.DataFrame(DataBike)
df_a.to_csv("aux94301.csv")  
aux94301 = pd.read_csv('aux94301.csv', low_memory=False)
aux94301['cantidad'] = aux94301['date']
aux94301 = aux94301.loc[:,['cantidad','Unnamed: 0']]
aux94301['date'] = aux94301['Unnamed: 0']
aux94301 = aux94301.loc[:,['cantidad','date']]
aux94301 = pd.merge(NotBike94301, aux94301, on='date', how='inner')
weather94301 = weather.groupby('zip_code')
weather94301 = weather94301.get_group(94301)
salida = pd.merge(weather94301, aux94301, on='date', how='inner')
salida.corr().loc[:,['cantidad']]

                                cantidad
max_temperature_f              -0.310852
mean_temperature_f             -0.298275
min_temperature_f              -0.223767
max_dew_point_f                -0.061328
mean_dew_point_f                0.024668
min_dew_point_f                 0.125192
max_humidity                    0.608986
mean_humidity                   0.657064
min_humidity                    0.474881
max_sea_level_pressure_inches   0.455782
mean_sea_level_pressure_inches  0.460742
min_sea_level_pressure_inches   0.494435
max_visibility_miles           -0.320594
mean_visibility_miles          -0.493439
min_visibility_miles           -0.634281
max_wind_Speed_mph             -0.286480
mean_wind_speed_mph            -0.413844
max_gust_speed_mph              0.674480
cloud_cover                     0.649614
wind_dir_degrees               -0.133335
zip_code                             NaN
id                             -0.365680
zipCode                              NaN
cantidad                        1.000000

In [101]:
#Dock
#Tambien relacion con casi todo
NotDocks94301 = NotDocks.groupby('zipCode')
NotDocks94301 = NotDocks94301.get_group(94301)
DataBike = NotDocks94301['date'].value_counts()
df_a = pd.DataFrame(DataBike)
df_a.to_csv("aux94301.csv")  
aux94301 = pd.read_csv('aux94301.csv', low_memory=False)
aux94301['cantidad'] = aux94301['date']
aux94301 = aux94301.loc[:,['cantidad','Unnamed: 0']]
aux94301['date'] = aux94301['Unnamed: 0']
aux94301 = aux94301.loc[:,['cantidad','date']]
aux94301 = pd.merge(NotDocks94301, aux94301, on='date', how='inner')
salida = pd.merge(weather94301, aux94301, on='date', how='inner')
salida.corr().loc[:,['cantidad']]

                                cantidad
max_temperature_f              -0.310852
mean_temperature_f             -0.298275
min_temperature_f              -0.223767
max_dew_point_f                -0.061328
mean_dew_point_f                0.024668
min_dew_point_f                 0.125192
max_humidity                    0.608986
mean_humidity                   0.657064
min_humidity                    0.474881
max_sea_level_pressure_inches   0.455782
mean_sea_level_pressure_inches  0.460742
min_sea_level_pressure_inches   0.494435
max_visibility_miles           -0.320594
mean_visibility_miles          -0.493439
min_visibility_miles           -0.634281
max_wind_Speed_mph             -0.286480
mean_wind_speed_mph            -0.413844
max_gust_speed_mph              0.674480
cloud_cover                     0.649614
wind_dir_degrees               -0.133335
zip_code                             NaN
id                             -0.365680
zipCode                              NaN
cantidad                        1.000000

In [ ]:
#Emos notados tres ciudades que hay una relacion entre los lugares vacios y las bicis y 2 que no
#Pero no son similares esas relaciones tampoco.
#Podriamos que suponer que hay una diferncia cultural sobre ir en bisicleta segun la ciudad.. O sino es simple concidencia.